config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
  #root to: 'users#index'
  resources :users, only: [:index, :show] do
    resources :foods, only: [:index, :show, :new, :create, :destroy]
    resources :recipes, only: [:index, :show, :new, :create, :destroy] do
      resources :general_shopping_lists, only: [:index]
      resources :recipe_foods, only: [:new, :edit, :create, :update, :destroy]
    end
    
  end
  #public recipes route
  resources :public_recipes, only: [:index]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :description, presence: true

  def total_price
    foods.sum('price  * recipe_foods.quantity')
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.where(user_id: current_user.id).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:user_id])
    @recipe = Recipe.find(params[:id])
    @foods = Food.all
    @recipe_foods = @recipe.recipe_foods.includes(:food, :recipe).order(:id)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @user = current_user
    @recipe = @user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to user_recipes_path(@user, @recipe)
    else
      render :new, alert: "Couldn't create recipe for user"
    end
  end

  def destroy
    @user = current_user
    @recipe = @user.recipes.find(params[:id])
    @recipe.destroy!
    redirect_to user_recipes_path
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public, :user_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<section class="container">
<div class="d-flex justify-content-end">
    <%= link_to 'Add New Recipe', new_user_recipe_path, class: "btn btn-primary" %>
    </div>
    <%if @recipes.any? %>
        <% @recipes.each do |recipe| %>
        <div class="row border border-0 mt-4 shadow p-3 mb-5 bg-body-tertiary rounded">
            <div class="d-flex flex-column col" >
                <%= link_to recipe.name, user_recipe_path(recipe.user_id, recipe), method: :get, class: "text-decoration-none text-black fs-2 fw-bold flex-grow-1" %>
                <% if can? :destroy, recipe %>
                    <p><%= button_to 'Remove', user_recipe_path(current_user, recipe), 
                        style: "border: none;
                                background: none;
                                text-decoration: underline;
                                color: blue;
                                text-transform: uppercase;", 
                        method: :delete %> 
                        </p>
                <% end %> 
            </div>
            <div class="col-8">
                <p class="flex-grow-1"><%= recipe.description %></p>
            </div>
        </div>
        <% end %>
        
    <% else %>
        <p>There are no recipes</p>
    <% end %>
</section>

app/views/recipes/new.html.erb
<section class="container">
  <div class="rounded-5 d-flex flex-column bg-secondary-subtle justify-content-center align-items-center mx-auto p-5 w-50">
  <h3>Create a new recipe</h3>
  <%= form_with model: @recipe, url: user_recipes_path, class: "w-100" do |f| %>
    <div class="form-group w-100">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control fs-4", style:"width: 100%" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :preparation_time %>
      <%= f.number_field :preparation_time, class:"form-control fs-4" %>
    </div>
    <div class="form-group">
      <%= f.label :cooking_time %>
      <%= f.number_field :cooking_time, class:"form-control fs-4" %>
    </div>
    <div class="form-check mt-2">
      <%= f.label :public, class: "form-check-label fs-4" %>
      <%= f.check_box :public, type: "checkbox", class:"form-check-input" %>
    </div>
    <div class="form-group mt-2">
      <div class= "d-flex justify-content-center gap-3 mt-3">
      <%= link_to 'Cancel', user_recipes_path(current_user), class: "btn btn-danger p-2 fs-5" %>      
      <%= f.submit class: "p-2 btn btn-primary fs-5" %>
      </div>
    </div>
  <% end %>
</section>

app/views/recipes/show.html.erb
<section class="container">
<div>
  <% if user_signed_in?%>
    <div>
      <%= link_to 'Back', user_recipes_path(current_user) %>      
    </div>
  <% end %>
  <h1 class="text-center"><%= @recipe.name %></h1>
  <% if can? :manage, @recipe or @recipe.public %>
      <div class="row">
        <div class="col-6 fs-4">
          <div><strong>Preparation Time:</strong> <%= @recipe.preparation_time %> hours(s)</div>
          <div><strong> Cooking Time:</strong> <%= @recipe.cooking_time %> hours(s)</div>
          <div><strong> Steps to go here...</strong></div>
        </div>
        <div class="col-6">
          <div class="form-check form-switch d-flex justify-content-end fs-4">
            <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault" 
              <% if @recipe.public %>
                checked='checked'
              <% end %>>
            <label class="form-check-label" for="flexSwitchCheckDefault">Public</label>
          </div>
        </div>
      </div>
  
    <% if can? :manage, @recipe %>
      <div class="d-flex justify-content-between my-3">
        <%= link_to "Generate Shopping List", user_recipe_general_shopping_lists_path(@user, @recipe), class: 'btn btn-secondary fs-4' %>
        <%= link_to "Add ingredient", new_user_recipe_recipe_food_path(@user, @recipe), class: 'btn btn-primary fs-4' %>
      </div>
    <% end %>
  <div class="bg-dark", style="height: 4px"> </div>
      <% if @recipe_foods.count > 0 %>
        <table class="table table-striped mt-5 fs-4">
            <thead class="table-secondary">
                <tr>
                    <th>Food</th>
                    <th>Quantity</th>
                    <th>Value</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @recipe_foods.each do |recipe_food| %>
                    <tr>
                        <td><%= recipe_food.food.name %></td>
                        <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
                        <td>$<%= recipe_food.quantity * recipe_food.food.price%></td>
                        
                        <% if can? :manage, recipe_food.recipe %>
                            <td class = "d-flex gap-2">
                              <%= link_to "Modify", edit_user_recipe_recipe_food_path(@user, @recipe, recipe_food)%>
                              <%= button_to "Remove", user_recipe_recipe_food_path(@user, @recipe, recipe_food),
                                style: "border: none;
                                      background: none;
                                      text-decoration: underline;
                                      color: blue;
                                      text-transform: uppercase;", 
                                method: :delete %>
                            </td>
                        <% end %>

                        <% if cannot? :manage , @recipe %>
                          <td>
                            <span>No actions for you here</span>
                          </td>
                        <% end %>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <% else %>
          <p class="text-danger text-center mt-5">There are no foods in this recipe</p>
        <% end %>
    <% else %>
      <p>Sorry, you don't have access to this recipe</p>
    <% end %> 
    <div>

</section>