config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
  #root to: 'users#index'
  resources :users, only: [:index, :show] do
    resources :foods, only: [:index, :show, :new, :create, :destroy]
    resources :recipes, only: [:index, :show, :new, :create, :destroy] do
      resources :general_shopping_lists, only: [:index]
      resources :recipe_foods, only: [:new, :edit, :create, :update, :destroy]
    end
    
  end
  #public recipes route
  resources :public_recipes, only: [:index]
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show destroy]
  before_action :set_user, only: %i[index show create]

  def index
    @foods = Food.where(user_id: params[:user_id])
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @user = User.find(params[:user_id])
    @food = @user.foods.new(**food_params)
    if @food.save
      flash[:success] = 'Food saved successfully'
      redirect_to user_foods_url
    else
      flash.now[:error] = 'Error: Food could not be saved'
      render :new
    end
  end

  def destroy
    @food.destroy
    flash[:success] = 'Food deleted successfully'
    redirect_to user_foods_url
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_food
    @food = set_user.foods.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<section class="container">
<div class="d-flex justify-content-end">
<%= link_to "Add Food", new_user_food_path, class: 'btn btn-primary mb-4' %>
</div>
<h4>Foods list</h4>
<table class="table table-striped fs-4">
  <thead class="table-secondary">
    <tr>
      <th>Name</th>
      <th>Measurement unit</th>
      <th>Price</th>
      <th colspan="3"> Actions </th>
    </tr>
  </thead>

  <tbody class="table-group-divider">
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td><strong> $ </strong> <%= food.price %> </td>
        <td><%= link_to 'Delete', user_food_path(current_user.id, food), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</section>

app/views/foods/new.html.erb
<section class="container">

<div class=" rounded-5 mx-auto d-flex flex-column justify-content-center align-items-center p-3 m bg-secondary-subtle", style= "width: 60%" >
<h1 class="text-center"> Create new food </h1>

<%= form_with model: @food, url: user_foods_path, class: "w-100" do |f| %>
  <div class="form-group mt-3">
    <%= f.text_field :name, placeholder:"Name", class: "w-100 form-control fs-5" %> <br/>
    
    <%= f.text_field :measurement_unit, placeholder:"Measurement unit", class: "w-100 form-control fs-5" %> <br/>
 
    <%= f.number_field :price, placeholder:"Price", class: "w-100 form-control fs-5" %> <br/>
   
    <%= f.number_field :quantity, placeholder:"Quantity", class: "w-100 form-control fs-5" %> <br/>
    <div class= "d-flex justify-content-center gap-3 mt-3">
      <%= link_to "Cancel", user_foods_path, class: "btn btn-danger p-3 fs-5" %>
      <%= f.submit class: "p-3 btn btn-primary fs-5" %>
    </div>
</div>
    
   </div>
<% end %>

</div>

</section>

app/views/foods/show.html.erb
<section class="container">
<h3> Are you sure you want to delete this ? </h3>
<h5><strong> name: </strong><%= @food.name %></h5>
<h5><strong>Measurement Unit: </strong> <%= @food.measurement_unit %></h5>
<h5><strong>Price: </strong><%= @food.price %></h5>
<h5><strong>Quantity: </strong> <%= @food.quantity %></h5>

<div class = "d-flex gap-4">
<%= button_to "Return to Foods Page", 
              user_foods_path,
              class: "btn btn-secondary",
              method: :get %>
              
              <%= button_to "Delete Food", 
              user_food_path(@user, @food),
              method: :delete, 
              class: "btn btn-danger" %> 


</section>