config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
  #root to: 'users#index'
  resources :users, only: [:index, :show] do
    resources :foods, only: [:index, :show, :new, :create, :destroy]
    resources :recipes, only: [:index, :show, :new, :create, :destroy] do
      resources :general_shopping_lists, only: [:index]
      resources :recipe_foods, only: [:new, :edit, :create, :update, :destroy]
    end
    
  end
  #public recipes route
  resources :public_recipes, only: [:index]
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :food, uniqueness: { scope: :recipe, case_sensitive: false, message: 'already exists in this recipe' }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[edit update destroy]
  before_action :set_recipe, only: %i[show edit new create destroy]
  before_action :set_food, only: %i[create update]
  before_action :set_user, only: %i[index show new edit create]

  def new
    @recipe_food = RecipeFood.new
  end

  def edit
    @recipe_food
  end

  def create
    @recipe_food = RecipeFood.new(recipe: @recipe, food: @food, quantity: recipe_food_params[:quantity])

    if @recipe_food.save
      flash[:success] = 'Recipe food was successfully created.'
      redirect_to user_recipe_url(@user, @recipe)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @recipe_food.update(food: @food, quantity: recipe_food_params[:quantity])
      flash[:success] = 'Recipe food was successfully updated.'
      redirect_to user_recipe_url(@user, @recipe)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @recipe_food.destroy
      flash[:success] = 'Recipe food was successfully removed.'
    else
      flash.now[:error] = 'Error: Recipe food could not be removed'
    end
    redirect_to user_recipe_url(@user, @recipe)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:user_id])
  end

  def set_recipe
    @recipe = set_user.recipes.find(params[:recipe_id])
  end

  def set_recipe_food
    @recipe_food = set_recipe.recipe_foods.find(params[:id])
  end

  def set_food
    @food = set_user.foods.find(recipe_food_params[:food_id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<div class=" mx-auto d-flex flex-column justify-content-center align-items-center p-3 m bg-secondary-subtle", style= "width: 60%" >
<%= form_with model: @recipe_food, url: user_recipe_recipe_foods_path, class: 'form w-50' do |form| %>
    <% if @recipe_food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>
  
        <ul>
          <% @recipe_food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div class="form flex flex-col">
    <div>
      <label class="form-label d-block">Quantity</label> <br/>
      <%= form.number_field :quantity, class: 'form-control' %> <br/>
    </div>
      
    <div class="form flex">
    <span class="">*Click to dropdown</span>
      <%= form.select :food_id, @user.foods.order(name: :asc).map { |f| [f.name, f.id]}, {}, class: "form-control" %>
    </div>
  
   <%= form.button "Add Ingredient", type: "submit", class: "btn btn-primary", 'data-ripple-light': true %>
   </div>
  <% end %>
</div>

app/views/recipe_foods/_update.html.erb
<div class=" mx-auto d-flex flex-column justify-content-center align-items-center p-3 m bg-secondary-subtle rounded-5", style= "width: 60%" >
<%= form_with model: @recipe_food, url: user_recipe_recipe_food_path, class: 'flex flex-col items-center w-6/12 mx-auto' do |form| %>
    <% if @recipe_food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>
  
        <ul>
          <% @recipe_food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="form-group input-group-outline mb-3">
      <label class="form-label fs-4"> Quantity </label> <br/>
      <%= form.number_field :quantity, class: 'form-control focus:border-blue-600 px-4 fs-4' %>
    </div>
  
    <span class="text-sm mt-2 text-gray-500 fs-4">*Click to dropdown</span>
    
    <div class="input-group input-group-outline mb-3">
      <%= form.select :food_id, @user.foods.order(name: :asc).map { |f| [f.name, f.id]}, {}, class: "form-control px-4 fs-4" %>
    </div>
  
    <%= form.button "Update Ingredient", type: "submit", class: "btn mb-5 btn-primary text-center", 'data-ripple-light': true %>
  <% end %>
  </div>

app/views/recipe_foods/edit.html.erb
<section class="container">
<h1 class="text-center">Edit Recipe Food</h1>
<%= render "update", recipe_food: @recipe_food %>
<br>
</section>

app/views/recipe_foods/new.html.erb
<section class = "container">
<h1 class="add-form">New recipe food</h1>
<br>
<%= render "form", recipe_food: @recipe_food %>
</section>