config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
  #root to: 'users#index'
  resources :users, only: [:index, :show] do
    resources :foods, only: [:index, :show, :new, :create, :destroy]
    resources :recipes, only: [:index, :show, :new, :create, :destroy] do
      resources :general_shopping_lists, only: [:index]
      resources :recipe_foods, only: [:new, :edit, :create, :update, :destroy]
    end
    
  end
  #public recipes route
  resources :public_recipes, only: [:index]
end

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top fs-3">
  <div class="container-fluid">
    <a class="navbar-brand fs-2 fw-bold" href="/">Railcipe</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to user_foods_path(current_user.id), class:"text-decoration-none", method: :get do %>  
          <span class="nav-link active text-decoration-none", aria-current="page"> Foods </span>
          <% end %>
        </li> |
        <li class="nav-item">
          <%= link_to "Recipe", user_recipes_path(current_user.id), method: :get, class:"nav-link" %>
        </li> |
        <li class="nav-item">
          <%= link_to "Public Recipes", public_recipes_path(current_user.id), method: :get, class:"nav-link" %>
        </li>
      <% end %>
      </ul>
      <% if user_signed_in? %>
    <%= button_to(
      "Log Out",
      destroy_user_session_path,
      method: :delete,
      class: "btn btn-primary"
    )%>
  <% else %>
   <%= button_to(
      "Sign In",
      new_user_session_path,
      method: :get,
      class: "btn btn-primary"
    )%>
  <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGroupProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body class="pt-5">
  <%= render 'layouts/nav_bar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
  </body>
</html>